### ISSUE TITLE
Add CONTRIBUTING

### ISSUE THREAD

**Issue by johnlees** [kidusasfaw/spatPomp#27]
For JOSS, add a community contributions guide, either as `.github/CONTRIBUTING` or in the README. This should contain info on:
1) How to contribute to the software 
2) How to report issues or problems with the software 
3) How to seek support

**Comment by kidusasfaw** [comment]
Hi @johnlees, thank you for pointing out this improvement to our package. I have now added a CONTRIBUTING markdown file to the root directory.

**Comment by johnlees** [comment]
Great, I will update the JOSS review
